[project]
name = "nico-ripser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ripser",
    "numpy",
    "matplotlib",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]